---

- name: Profil EyeTroduit
  strategy: free
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Apt update
    apt:
      update_cache: yes
  - name: Update packages
    apt:
      name: "*"
      state: latest
  - name: Install packages
    apt:
      name:
        - apache2
        - libapache2-mod-wsgi-py3
        - python3.8-venv
        - certbot
        - python3-certbot-apache
        - tor
  - name: create directory
    file:
      path: /var/www/eyetroduit
      state: directory
      mode: "u=rwx,g=wx,o="
  - name: create directory
    file:
      path: /var/www/root
      state: directory
      mode: "u=rwx,g=wx,o="
  - name: remove github copy
    shell: /bin/rm -rf /tmp/repos
  - name: Clone github repository
    git:
      repo: git@github.com:Th4nat0s/eyetroduit.git
      dest: /tmp/repos/
      clone: yes
      update: yes
      accept_hostkey: yes
    become: no
  - name: remove .git
    shell: /bin/rm -rf /tmp/repos/.git
  - name: push in folder
    copy:
      src: /tmp/repos/webapp/
      dest: /var/www/eyetroduit
      remote_src: yes
  - name: push in folder
    copy:
      src: /tmp/repos/root/
      dest: /var/www/root
      remote_src: yes
  - name: Créer le répertoire pour l'environnement virtuel
    file:
      path: /var/www/eyetroduit/venv_eyetroduit
      state: directory
      mode: "u=rwx,g=wx,o="
  - name: create venv
    shell: python3 -m venv /var/www/eyetroduit/venv_eyetroduit
  - name: install pip packages
    ansible.builtin.pip:
      requirements: /var/www/eyetroduit/requirements.txt
      virtualenv: /var/www/eyetroduit/venv_eyetroduit
  - name: Copy apache conh
    copy:
      src: /tmp/repos/deployement/002-eyetroduit.conf
      dest: /etc/apache2/sites-available
      remote_src: yes
  - name: Copy datatbase
    copy:
      src: /var/www/eyetroduit/app_template.db
      dest: /var/www/eyetroduit/app.db
      remote_src: yes
  - name: copy setup
    copy:
      src: /var/www/eyetroduit/config_template.py
      dest: /var/www/eyetroduit/config.py
      remote_src: yes
  - name: Create certbot folder
    shell:  mkdir /var/www/html/.well-known/acme-challenge -p
  - name: Attrib www rights
    shell: chown www-data:www-data /var/www/eyetroduit
  - name: Attrib www root rights
    shell: chown www-data:www-data /var/www/root
  - name: Attrib certbot rights
    shell: chown www-data:www-data /var/www/html/.well-known/acme-challenge
  - name: create certbot folder
    shell: mkdir -p /etc/letsencrypt/live/xakep.in
  - name: create root folder
    shell: mkdir -p /var/www/root
  - name: Create certs
    shell: openssl req -new -x509 -nodes -out /etc/letsencrypt/live/xakep.in/cert.pem -keyout /etc/letsencrypt/live/xakep.in/privkey.pem -days 365 -subj "/CN=xakep.in"
  - name: disable default apache sites
    shell: a2dissite 000-default
  - name: enable wesite
    shell: a2ensite 002-eyetroduit
  #- name: enable ssl
  #  shell: a2enmod ssl
  - name: startapache
    shell: systemctl start apache2
  - name: launch certbot
    shell: sudo certbot --apache -m alt.x3-1oqf7v3a@whatagarbage.com --agree-tos -n  --domains xakep.in
  - name: restartapache
    shell: systemctl restart apache2
