---

- name: Profil EyeTroduit
  strategy: free
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Apt update
    apt:
      update_cache: yes
  - name: Update packages
    apt:
      name: "*"
      state: latest
  - name: remove github copy
    shell: /bin/rm -rf /tmp/repos
  - name: Clone github repository
    git:
      repo: git@github.com:Th4nat0s/eyetroduit.git
      dest: /tmp/repos/
      clone: yes
      update: yes
      accept_hostkey: yes
    become: no
  - name: remove .git
    shell: /bin/rm -rf /tmp/repos/.git
  - name: push in folder
    copy:
      src: /tmp/repos/webapp/
      dest: /var/www/eyetroduit
      remote_src: yes
      owner: www-data
  - name: push in folder
    copy:
      src: /tmp/repos/root/
      dest: /var/www/root
      remote_src: yes
      owner: www-data
  - name: Créer le répertoire pour l'environnement virtuel
    file:
      path: /var/www/eyetroduit/venv_eyetroduit
      state: directory
      mode: "u=rwx,g=wx,o="
  - name: create venv
    shell: python3 -m venv /var/www/eyetroduit/venv_eyetroduit
  - name: install pip packages
    ansible.builtin.pip:
      requirements: /var/www/eyetroduit/requirements.txt
      virtualenv: /var/www/eyetroduit/venv_eyetroduit
  - name: Attrib www rights
    shell: chown www-data:www-data /var/www/eyetroduit
  - name: Attrib www root rights
    shell: chown www-data:www-data /var/www/root
  - name: Attrib certbot rights
    shell: chown www-data:www-data /var/www/html/.well-known/acme-challenge
  - name: startapache
    shell: systemctl restart apache2
